main:
  - name: About
    url: /about/
    weight: -110
  - name: Posts
    url: /posts/
    weight: -100

footer:
  - name: About
    url: /about/
    weight: -110
  - name: Browse
    url: /browse/
    weight: -100